config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"
  get "home/about" => "homes#about", as: "homes_about"

  devise_for :users
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:edit, :update, :show, :index] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, {presence: true}
  validates :body, {presence: :true, length: { maximum: 200 }}

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :view_counts, dependent: :destroy


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: :true, length: { maximum: 140 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 validates :name, {length: { minimum: 2, maximum: 20 }, uniqueness: true}
 validates :introduction, length: { maximum: 50 }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :view_counts, dependent: :destroy

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/NoImage.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/view_count.rb
class ViewCount < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_matching_login_user, only: [:edit]

  def index
    # @books = Book.all
    @books = Book.left_joins(:favorites).group(:id).order('count(favorites.id) desc')
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id

    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end

  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def show
    @book = Book.find(params[:id])
    @comment = BookComment.new
    @comments = @book.book_comments
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)

    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create(user_id: current_user.id)
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
    # redirect_to room_path(@room)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      @myUserId = current_user.id
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end

  end

  def show
    @user = User.find(params[:id])
    @books = @user.books

    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_leftbar.html.erb
    <div class="left-bar col-md-3 my-3">
      <h2>User info</h2>

      <%= image_tag current_user.get_profile_image(100,100) %>

      <table class="table">
        <tr>
          <td>name</td>
          <td><%= current_user.name %></td>
        </tr>
          <td>introduction</td>
          <td><%= current_user.introduction %></td>
      </table>

      <a href="<%= edit_user_path(current_user.id) %>">
        <button type="button" class="border-1 w-75 mt-2 btn btn-secondary"><i class="fas fa-user-cog"></i></button>
      </a>

      <h2>New book</h2>

      <%= form_with model: Book.new, url: books_path, method: :post do |f| %>

        Title<br>
        <%= f.text_field :title %>
        <br>
        Opinion<br>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class: 'button btn-success border-0 rounded p-2' %>
      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="co-lg-12 mx-auto my-3">

      <% if @book.errors.any? %>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

      <h1>Editing Book</h1>

      <%= form_with model:@book do |f| %>
        Title<br>
        <%= f.text_field :title %><br>
        Opinion<br>
        <%= f.text_area :body%><br>
        <%= f.submit 'Update Book', class: 'btn btn-success'%>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>｜<%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row my-3">

    <% if @book.errors.any? %>
      <%= @book.errors.count %> errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

  </div>
</div>

<div class="container">
  <div class="row">

    <%= render 'leftbar' %>

    <div class="right-bar col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>

        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id)%></td>
          <td><%= book.body %></td>
          <td>
            <% if book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(book.id), method: :delete do %>
                <p class="text-danger">♥<%= book.favorites.count %></p>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(book.id), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <td>コメント数: <%= book.book_comments.count %></td>
          <td>閲覧数：<%= book.view_counts.count %></td>
        </tr>
        <% end %>

      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">



    <div class="left-bar col-md-3 my-3">
      <h2>User info</h2>

      <%= image_tag @book.user.get_profile_image(100,100) %>

      <table class="table">
        <tr>
          <td>name</td>
          <td><%= @book.user.name %></td>
        </tr>
          <td>introduction</td>
          <td><%= @book.user.introduction %></td>
      </table>

      <a href="<%= edit_user_path(@book.user_id) %>">
        <button type="button" class="border-1 w-75 mt-2 btn btn-secondary"><i class="fas fa-user-cog"></i></button>
      </a>

      <h2>New book</h2>

      <%= form_with model: Book.new, url: books_path, method: :post do |f| %>

        Title<br>
        <%= f.text_field :title %>
        <br>
        Opinion<br>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class: 'button btn-success border-0 rounded p-2' %>
      <% end %>
    </div>



    <div class="right-bar col-md-8 offset-md-1 my-3">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %><br><%= @book.user.name %>
              <% end %>
              </td>
          <td><%= link_to @book.title, book_path(@book.id)%></td>
          <td><%= @book.body %></td>
          <td>
            <% if @book.favorited_by?(current_user) %>
              <%= link_to book_favorites_path(@book.id), method: :delete do %>
                <p class="text-danger">♥<%= @book.favorites.count %></p>
              <% end %>
            <% else %>
              <%= link_to book_favorites_path(@book.id), method: :post do %>
                ♡<%= @book.favorites.count %>
              <% end %>
            <% end %>
          </td>
          <td>コメント数: <%= @book.book_comments.count %></td>
          <td>閲覧数：<%= @book.view_counts.count %></td>

          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book.id), method: :get, class: 'btn btn-success text-light' %></td>
            <td><%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-danger text-light' %></td>
          <% end %>
        </tr>
      </table>

      <% @comments.each do |comment| %>
        <div class="mb-1">
          <%= image_tag comment.user.get_profile_image(50,50) %>

          <%= comment.comment %>
          <% if comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(comment.book_id, comment), method: :delete, class: "btn btn-danger" %>
          <% end %>
          <br><%= link_to comment.user.name, user_path(comment.user_id) %>
        </div>
      <% end %>

      <div>
        <%= form_with model: [@book, @comment] do |f| %>
          <%= f.text_area :comment %>
          <%= f.submit "送信" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<% @entries.each do |e| %>
  <% if @myUserId != e.user.id %>
    <h2><%= e.user.name %>さんとのトークルーム</h2>
  <% end %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

  <% if @messages.present? %>
    <% @messages.each do |m|  %>
      <p><%= m.user.name %></p>
      <p><%= m.message %></p>
    <% end %>
  <% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :message, placeholder: "メッセージを入力してください", size: 140, class: "form-text-field" %>
  <%= f.hidden_field :room_id, value: @room.id  %>
  <%= f.submit "投稿", class: "form-submit"  %>
<% end  %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="co-lg-12 mx-auto my-3">

      <% if @user.errors.any? %>
      <%= @user.errors.count %> errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
    <% end %>

      <h1>User info</h1>

      <%= form_with model:@user, url: user_path(@user.id), method: :patch do |f| %>

      Name<br>
      <%= f.text_field :name %><br>

      Image<br>
      <%= f.file_field :profile_image %><br>

      Introduction<br>
      <%= f.text_area :introduction %><br>

      <%= f.submit 'Update User' %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <%= render 'books/leftbar' %>

    <div class="right-bar col-md-8 offset-md-1 my-3">
      <h2>Users</h2>
      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
        <tr>
          <% @users.each do |user| %>
          <td><%= image_tag user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td>フォロー数<%= user.followings.count %></td>
          <td>フォロワー数<%= user.followers.count %></td>
          <td><%= render "relationships/btn", user: user %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
          <% end %>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">



    <div class="left-bar col-md-3 my-3">
      <h2>User info</h2>

      <%= image_tag @user.get_profile_image(100,100) %>

      <table class="table">
        <tr>
          <td>name</td>
          <td><%= @user.name %></td>
        </tr>
          <td>introduction</td>
          <td><%= @user.introduction %></td>
        <tr>
          <td>follows</td>
          <td><%= link_to @user.followings.count, user_followings_path(@user.id) %></td>
        </tr>
        <tr>
          <td>followers</td>
          <td><%= link_to @user.followers.count, user_followers_path(@user.id) %></td>
        </tr>
      </table>

      <% if current_user == @user %>
        <a href="<%= edit_user_path(@user.id) %>">
          <button type="button" class="border-1 w-75 mt-2 btn btn-secondary"><i class="fas fa-user-cog"></i></button>
        </a>
      <% else %>
        <td><%= render "relationships/btn", user: @user %></td>
        <% if (current_user.following?(@user)) && (@user.following?(current_user)) %>
          <% if @isRoom == true %>
            <!--<p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary mt-1">チャットへ</a></p>-->
            <%= link_to "チャットへ", room_path(@roomId), class: "btn btn-primary mt-1" %>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.submit "チャットを始める", class: "btn btn-primaru mt-1 user-show-chat" %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>

      <h2>New book</h2>

      <%= form_with model: Book.new, url: books_path, method: :post do |f| %>

        Title<br>
        <%= f.text_field :title %>
        <br>
        Opinion<br>
        <%= f.text_area :body %>
        <br>
        <%= f.submit 'Create Book', class: 'button btn-success border-0 rounded p-2' %>
      <% end %>
    </div>



    <div class="right-bar col-md-8 offset-md-1 my-3">
      <h2>Books</h2>
      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <tr>
          <% @books.each do |book| %>
          <td>
            <%= link_to user_path(book.user_id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
          <% end %>
      </table>
    </div>

  </div>
</div>